### ISSUE TITLE
Add null safety 

### ISSUE THREAD

**Issue by ikramhasan** [zoharcochavi/dotfield#2]
Thanks for creating this awesome package. I'm using it in my [Impossible tic tac toe web app](https://impossible-tictactoe.web.app/) I would highly appreciate it if you could add null safety to this project so that I can migrate my app to sound null safety.

**Comment by cochaviz** [comment]
Hey! Than you so much! Never thought somebody would actually use this package!

Yeah, I can totally make sure that it is null safe. I have time the coming days, so you can expect an update somewhere then!

**Comment by cochaviz** [comment]
Done! If you have any other suggestions or requests, please let me know!
